# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [27]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds
1,1,Rikitea,PF,-23.1203,-134.9692,69.17,68,95,22.19,overcast clouds
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky
3,3,Port Alfred,ZA,-33.5906,26.8910,67.17,71,100,5.99,overcast clouds
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds
5,5,Yelan,RU,50.9490,43.7378,53.55,56,100,11.90,overcast clouds
6,6,Mataura,NZ,-46.1927,168.8643,43.48,89,59,3.89,broken clouds
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky
8,8,Broome,US,42.2506,-75.8330,57.36,86,0,4.61,clear sky
9,9,Polyarnyy,RU,69.1989,33.4478,48.09,82,100,28.30,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 76
What is the maximum temperature you would like for your trip? 91

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [7]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

# Display sample data
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky
...,...,...,...,...,...,...,...,...,...,...
649,649,Santiago De Cuba,CU,20.0247,-75.8219,82.51,74,20,9.22,few clouds
652,652,Mabaruma,GY,8.2000,-59.7833,87.80,59,45,5.59,scattered clouds
653,653,Tual,ID,-5.6667,132.7500,83.35,78,100,16.89,overcast clouds
658,658,Buchanan,LR,5.8808,-10.0467,81.63,73,78,8.90,light rain
663,663,Vasai,IN,19.4700,72.8000,82.49,78,100,4.83,overcast clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [6]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky
...,...,...,...,...,...,...,...,...,...,...
649,649,Santiago De Cuba,CU,20.0247,-75.8219,82.51,74,20,9.22,few clouds
652,652,Mabaruma,GY,8.2000,-59.7833,87.80,59,45,5.59,scattered clouds
653,653,Tual,ID,-5.6667,132.7500,83.35,78,100,16.89,overcast clouds
658,658,Buchanan,LR,5.8808,-10.0467,81.63,73,78,8.90,light rain
663,663,Vasai,IN,19.4700,72.8000,82.49,78,100,4.83,overcast clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [12]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_travel_cities.copy(["City", "Country", "Max Temp", "Weather", "Lat", "Lng"])

# Display sample data
hotel_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky
...,...,...,...,...,...,...,...,...,...,...
649,649,Santiago De Cuba,CU,20.0247,-75.8219,82.51,74,20,9.22,few clouds
652,652,Mabaruma,GY,8.2000,-59.7833,87.80,59,45,5.59,scattered clouds
653,653,Tual,ID,-5.6667,132.7500,83.35,78,100,16.89,overcast clouds
658,658,Buchanan,LR,5.8808,-10.0467,81.63,73,78,8.90,light rain
663,663,Vasai,IN,19.4700,72.8000,82.49,78,100,4.83,overcast clouds

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [13]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather,Hotel Name
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds,
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky,
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds,
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky,
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky,
...,...,...,...,...,...,...,...,...,...,...,...
649,649,Santiago De Cuba,CU,20.0247,-75.8219,82.51,74,20,9.22,few clouds,
652,652,Mabaruma,GY,8.2000,-59.7833,87.80,59,45,5.59,scattered clouds,
653,653,Tual,ID,-5.6667,132.7500,83.35,78,100,16.89,overcast clouds,
658,658,Buchanan,LR,5.8808,-10.0467,81.63,73,78,8.90,light rain,
663,663,Vasai,IN,19.4700,72.8000,82.49,78,100,4.83,overcast clouds,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [14]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [15]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [20]:
# Display sample data
hotel_df.head(40)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather,Hotel Name
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds,"ZINGARA 76ft Catamaran, full crew-all included"
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky,"Sea Lounge! Bar, Club & Restaurant"
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds,Hotel Narayan Avezika Comfort
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky,Sur Plaza Hotel
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky,ibis Styles Karratha
12,12,Natal,BR,-5.7950,-35.2094,86.65,62,75,12.66,broken clouds,Villa Park Hotel | Natal
16,16,Kirakira,SB,-10.4544,161.9205,78.10,86,100,6.62,overcast clouds,SanBiz Lodge
20,20,Ugoofaaru,MV,5.6667,73.0000,81.64,77,93,18.75,overcast clouds,Ungoofaaru Inn
22,22,Trairi,BR,-3.2778,-39.2689,87.17,52,48,16.37,scattered clouds,janelas do mar
24,24,Cockburn Town,TC,21.4612,-71.1419,82.89,73,99,10.54,overcast clouds,Osprey Beach Hotel
29,29,Butaritari,KI,3.0707,172.7902,81.27,79,10,15.08,light rain,Isles Sunset Lodge
31,31,Unai,BR,-16.3575,-46.9061,87.19,41,98,6.98,overcast clouds,Hotel Regente
39,39,Salalah,OM,17.0151,54.0924,82.49,78,40,11.50,scattered clouds,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
40,40,Bubaque,GW,11.2833,-15.8333,82.04,68,19,5.55,few clouds,"Casa Dora, Bubaque"
46,46,Victoria,HK,22.2855,114.1577,85.17,78,21,11.01,few clouds,Mini Central
49,49,Georgetown,MY,5.4112,100.3354,82.33,87,40,3.44,thunderstorm with light rain,Cititel Penang
55,55,Tambopata,PE,-12.7333,-69.1833,76.89,88,20,4.61,few clouds,Enashawa Lodge
56,56,Mitsamiouli,KM,-11.3847,43.2844,78.39,68,27,5.12,scattered clouds,Foyer ADM
59,59,Ponta Do Sol,PT,32.6667,-17.1000,79.72,68,29,2.26,scattered clouds,Hotel do Campo
60,60,Lata,PT,40.1629,-8.3327,86.07,23,100,1.21,overcast clouds,Casa Maquia
61,61,Hirara,JP,24.8000,125.2833,82.04,73,85,15.70,overcast clouds,Hotel Atoll Emerald Miyakojima
62,62,Hilo,US,19.7297,-155.0900,79.29,94,100,4.61,overcast clouds,Hilo Hawaiian Hotel
64,64,Prado,BR,-17.3411,-39.2208,80.20,63,96,8.34,overcast clouds,INN CORNER RIVER - PRADO - BAHIA - HOUSING AND...
66,66,Arraial Do Cabo,BR,-22.9661,-42.0278,76.86,69,40,14.97,scattered clouds,Pousada Porto Praia
67,67,Fare,PF,-16.7000,-151.0167,77.49,75,5,26.19,clear sky,Maitai Lapita Village Huahine
72,72,Mugumu,TZ,-1.8500,34.7000,80.44,31,96,5.84,overcast clouds,Lemala Mara
76,76,Port Blair,IN,11.6667,92.7500,81.45,77,100,7.72,overcast clouds,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
82,82,Boffa,GN,10.1667,-14.0333,89.51,68,35,3.94,light rain,Hôtel Niara Belly
84,84,Sao Filipe,CV,14.8961,-24.4956,80.62,80,13,12.48,few clouds,Hotel Xaguate
85,85,Cabedelo,BR,-6.9811,-34.8339,84.87,72,25,11.25,scattered clouds,Pousada Camboinha
87,87,Ambon,ID,-3.6954,128.1814,78.94,89,20,8.05,few clouds,Swiss-Belhotel Ambon
88,88,Maragogi,BR,-9.0122,-35.2225,82.26,66,35,9.28,scattered clouds,Salinas do Maragogi All Inclusive Resort
93,93,Thinadhoo,MV,0.5333,72.9333,82.33,77,88,21.27,overcast clouds,
94,94,Mount Isa,AU,-20.7333,139.5000,82.17,51,100,0.00,light rain,ibis Styles Mt Isa Verona
95,95,Malanje,AO,-9.5402,16.3410,84.25,40,96,6.04,overcast clouds,Hotel Ginga
98,98,General Salgado,BR,-20.6483,-50.3606,87.37,42,48,13.09,scattered clouds,TUTU HOTEL
103,103,Costa Rica,BR,-23.4167,-54.6500,76.82,81,100,13.00,moderate rain,
107,107,Argostolion,GR,38.1811,20.4890,77.07,41,20,10.36,few clouds,Princess Hotel
109,109,Kupang,ID,-10.1667,123.5833,81.10,78,98,12.55,overcast clouds,Hotel On The Rock by Prasanthi
114,114,Beira,MZ,-19.8436,34.8389,84.29,70,20,17.27,few clouds,Beira Terrace Hotel

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [28]:
# Replace empty strings with NaN values for Hotel Name column
hotel_df["Hotel Name"].replace('', np.nan, inplace=True)

hotel_df.head(40)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather,Hotel Name
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds,"ZINGARA 76ft Catamaran, full crew-all included"
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky,"Sea Lounge! Bar, Club & Restaurant"
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds,Hotel Narayan Avezika Comfort
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky,Sur Plaza Hotel
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky,ibis Styles Karratha
12,12,Natal,BR,-5.7950,-35.2094,86.65,62,75,12.66,broken clouds,Villa Park Hotel | Natal
16,16,Kirakira,SB,-10.4544,161.9205,78.10,86,100,6.62,overcast clouds,SanBiz Lodge
20,20,Ugoofaaru,MV,5.6667,73.0000,81.64,77,93,18.75,overcast clouds,Ungoofaaru Inn
22,22,Trairi,BR,-3.2778,-39.2689,87.17,52,48,16.37,scattered clouds,janelas do mar
24,24,Cockburn Town,TC,21.4612,-71.1419,82.89,73,99,10.54,overcast clouds,Osprey Beach Hotel
29,29,Butaritari,KI,3.0707,172.7902,81.27,79,10,15.08,light rain,Isles Sunset Lodge
31,31,Unai,BR,-16.3575,-46.9061,87.19,41,98,6.98,overcast clouds,Hotel Regente
39,39,Salalah,OM,17.0151,54.0924,82.49,78,40,11.50,scattered clouds,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
40,40,Bubaque,GW,11.2833,-15.8333,82.04,68,19,5.55,few clouds,"Casa Dora, Bubaque"
46,46,Victoria,HK,22.2855,114.1577,85.17,78,21,11.01,few clouds,Mini Central
49,49,Georgetown,MY,5.4112,100.3354,82.33,87,40,3.44,thunderstorm with light rain,Cititel Penang
55,55,Tambopata,PE,-12.7333,-69.1833,76.89,88,20,4.61,few clouds,Enashawa Lodge
56,56,Mitsamiouli,KM,-11.3847,43.2844,78.39,68,27,5.12,scattered clouds,Foyer ADM
59,59,Ponta Do Sol,PT,32.6667,-17.1000,79.72,68,29,2.26,scattered clouds,Hotel do Campo
60,60,Lata,PT,40.1629,-8.3327,86.07,23,100,1.21,overcast clouds,Casa Maquia
61,61,Hirara,JP,24.8000,125.2833,82.04,73,85,15.70,overcast clouds,Hotel Atoll Emerald Miyakojima
62,62,Hilo,US,19.7297,-155.0900,79.29,94,100,4.61,overcast clouds,Hilo Hawaiian Hotel
64,64,Prado,BR,-17.3411,-39.2208,80.20,63,96,8.34,overcast clouds,INN CORNER RIVER - PRADO - BAHIA - HOUSING AND...
66,66,Arraial Do Cabo,BR,-22.9661,-42.0278,76.86,69,40,14.97,scattered clouds,Pousada Porto Praia
67,67,Fare,PF,-16.7000,-151.0167,77.49,75,5,26.19,clear sky,Maitai Lapita Village Huahine
72,72,Mugumu,TZ,-1.8500,34.7000,80.44,31,96,5.84,overcast clouds,Lemala Mara
76,76,Port Blair,IN,11.6667,92.7500,81.45,77,100,7.72,overcast clouds,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
82,82,Boffa,GN,10.1667,-14.0333,89.51,68,35,3.94,light rain,Hôtel Niara Belly
84,84,Sao Filipe,CV,14.8961,-24.4956,80.62,80,13,12.48,few clouds,Hotel Xaguate
85,85,Cabedelo,BR,-6.9811,-34.8339,84.87,72,25,11.25,scattered clouds,Pousada Camboinha
87,87,Ambon,ID,-3.6954,128.1814,78.94,89,20,8.05,few clouds,Swiss-Belhotel Ambon
88,88,Maragogi,BR,-9.0122,-35.2225,82.26,66,35,9.28,scattered clouds,Salinas do Maragogi All Inclusive Resort
93,93,Thinadhoo,MV,0.5333,72.9333,82.33,77,88,21.27,overcast clouds,NaN
94,94,Mount Isa,AU,-20.7333,139.5000,82.17,51,100,0.00,light rain,ibis Styles Mt Isa Verona
95,95,Malanje,AO,-9.5402,16.3410,84.25,40,96,6.04,overcast clouds,Hotel Ginga
98,98,General Salgado,BR,-20.6483,-50.3606,87.37,42,48,13.09,scattered clouds,TUTU HOTEL
103,103,Costa Rica,BR,-23.4167,-54.6500,76.82,81,100,13.00,moderate rain,NaN
107,107,Argostolion,GR,38.1811,20.4890,77.07,41,20,10.36,few clouds,Princess Hotel
109,109,Kupang,ID,-10.1667,123.5833,81.10,78,98,12.55,overcast clouds,Hotel On The Rock by Prasanthi
114,114,Beira,MZ,-19.8436,34.8389,84.29,70,20,17.27,few clouds,Beira Terrace Hotel

In [29]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

# Display sample data
clean_hotel_df.head(40)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather,Hotel Name
0,0,Road Town,VG,18.4167,-64.6167,87.89,79,75,11.50,broken clouds,"ZINGARA 76ft Catamaran, full crew-all included"
2,2,Itarema,BR,-2.9248,-39.9167,86.95,56,6,18.68,clear sky,"Sea Lounge! Bar, Club & Restaurant"
4,4,Dwarka,IN,22.2394,68.9678,83.19,68,75,11.59,broken clouds,Hotel Narayan Avezika Comfort
7,7,Sur,OM,22.5667,59.5289,86.70,53,0,4.74,clear sky,Sur Plaza Hotel
10,10,Karratha,AU,-20.7377,116.8463,76.75,57,10,15.90,clear sky,ibis Styles Karratha
12,12,Natal,BR,-5.7950,-35.2094,86.65,62,75,12.66,broken clouds,Villa Park Hotel | Natal
16,16,Kirakira,SB,-10.4544,161.9205,78.10,86,100,6.62,overcast clouds,SanBiz Lodge
20,20,Ugoofaaru,MV,5.6667,73.0000,81.64,77,93,18.75,overcast clouds,Ungoofaaru Inn
22,22,Trairi,BR,-3.2778,-39.2689,87.17,52,48,16.37,scattered clouds,janelas do mar
24,24,Cockburn Town,TC,21.4612,-71.1419,82.89,73,99,10.54,overcast clouds,Osprey Beach Hotel
29,29,Butaritari,KI,3.0707,172.7902,81.27,79,10,15.08,light rain,Isles Sunset Lodge
31,31,Unai,BR,-16.3575,-46.9061,87.19,41,98,6.98,overcast clouds,Hotel Regente
39,39,Salalah,OM,17.0151,54.0924,82.49,78,40,11.50,scattered clouds,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
40,40,Bubaque,GW,11.2833,-15.8333,82.04,68,19,5.55,few clouds,"Casa Dora, Bubaque"
46,46,Victoria,HK,22.2855,114.1577,85.17,78,21,11.01,few clouds,Mini Central
49,49,Georgetown,MY,5.4112,100.3354,82.33,87,40,3.44,thunderstorm with light rain,Cititel Penang
55,55,Tambopata,PE,-12.7333,-69.1833,76.89,88,20,4.61,few clouds,Enashawa Lodge
56,56,Mitsamiouli,KM,-11.3847,43.2844,78.39,68,27,5.12,scattered clouds,Foyer ADM
59,59,Ponta Do Sol,PT,32.6667,-17.1000,79.72,68,29,2.26,scattered clouds,Hotel do Campo
60,60,Lata,PT,40.1629,-8.3327,86.07,23,100,1.21,overcast clouds,Casa Maquia
61,61,Hirara,JP,24.8000,125.2833,82.04,73,85,15.70,overcast clouds,Hotel Atoll Emerald Miyakojima
62,62,Hilo,US,19.7297,-155.0900,79.29,94,100,4.61,overcast clouds,Hilo Hawaiian Hotel
64,64,Prado,BR,-17.3411,-39.2208,80.20,63,96,8.34,overcast clouds,INN CORNER RIVER - PRADO - BAHIA - HOUSING AND...
66,66,Arraial Do Cabo,BR,-22.9661,-42.0278,76.86,69,40,14.97,scattered clouds,Pousada Porto Praia
67,67,Fare,PF,-16.7000,-151.0167,77.49,75,5,26.19,clear sky,Maitai Lapita Village Huahine
72,72,Mugumu,TZ,-1.8500,34.7000,80.44,31,96,5.84,overcast clouds,Lemala Mara
76,76,Port Blair,IN,11.6667,92.7500,81.45,77,100,7.72,overcast clouds,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
82,82,Boffa,GN,10.1667,-14.0333,89.51,68,35,3.94,light rain,Hôtel Niara Belly
84,84,Sao Filipe,CV,14.8961,-24.4956,80.62,80,13,12.48,few clouds,Hotel Xaguate
85,85,Cabedelo,BR,-6.9811,-34.8339,84.87,72,25,11.25,scattered clouds,Pousada Camboinha
87,87,Ambon,ID,-3.6954,128.1814,78.94,89,20,8.05,few clouds,Swiss-Belhotel Ambon
88,88,Maragogi,BR,-9.0122,-35.2225,82.26,66,35,9.28,scattered clouds,Salinas do Maragogi All Inclusive Resort
94,94,Mount Isa,AU,-20.7333,139.5000,82.17,51,100,0.00,light rain,ibis Styles Mt Isa Verona
95,95,Malanje,AO,-9.5402,16.3410,84.25,40,96,6.04,overcast clouds,Hotel Ginga
98,98,General Salgado,BR,-20.6483,-50.3606,87.37,42,48,13.09,scattered clouds,TUTU HOTEL
107,107,Argostolion,GR,38.1811,20.4890,77.07,41,20,10.36,few clouds,Princess Hotel
109,109,Kupang,ID,-10.1667,123.5833,81.10,78,98,12.55,overcast clouds,Hotel On The Rock by Prasanthi
114,114,Beira,MZ,-19.8436,34.8389,84.29,70,20,17.27,few clouds,Beira Terrace Hotel
116,116,Marsh Harbour,BS,26.5412,-77.0636,78.64,65,9,13.53,clear sky,Abaco Beach Resort
117,117,Babol,IR,36.5513,52.6790,78.87,73,0,0.00,clear sky,Reza Hotel

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [ ]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [30]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [33]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Weather} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [34]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]


# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>ZINGARA 76ft Catamaran, full crew-all included</dd>\n<dt>City</dt><dd>Road Town</dd>\n<dt>Country</dt><dd>VG</dd>\n<dt>Current Weather</dt><dd>broken clouds and 87.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sea Lounge! Bar, Club & Restaurant</dd>\n<dt>City</dt><dd>Itarema</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>clear sky and 86.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Narayan Avezika Comfort</dd>\n<dt>City</dt><dd>Dwarka</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>broken clouds and 83.19 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sur Plaza Hotel</dd>\n<dt>City</dt><dd>Sur</dd>\n<dt>Country</dt><dd>OM</dd>\n<dt>Current Weather</dt><dd>clear sky and 86.7 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ibis Styles Karratha</dd>\n<dt>City</dt><dd>Karratha</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.75 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Villa Park Hotel | Natal</dd>\n<dt>City</dt><dd>Natal</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>broken clouds and 86.65 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>SanBiz Lodge</dd>\n<dt>City</dt><dd>Kirakira</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.1 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Ungoofaaru Inn</dd>\n<dt>City</dt><dd>Ugoofaaru</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 81.64 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>janelas do mar</dd>\n<dt>City</dt><dd>Trairi</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 87.17 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Osprey Beach Hotel</dd>\n<dt>City</dt><dd>Cockburn Town</dd>\n<dt>Country</dt><dd>TC</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 82.89 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [35]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
0   18.4167  -64.6167
2   -2.9248  -39.9167
4   22.2394   68.9678
7   22.5667   59.5289
10 -20.7377  116.8463
12  -5.7950  -35.2094
16 -10.4544  161.9205
20   5.6667   73.0000
22  -3.2778  -39.2689
24  21.4612  -71.1419

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [37]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Create a figure to add the Google map as a layer
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))